### ISSUE TITLE
Enumerate limited by HNF or concentration

### ISSUE THREAD

**Issue by rosenbrockc** [wsmorgan/phonon-enumeration#21]
The `enum.in` file can only be created at the moment limited by cell size. I need to enumerate all the structures of a given cell shape and size, but no others. I can hack the code to only write out the entry to enum.in if the HNF matches, but it ought to be an option like:

``` bash
enumeration.py -distrib all all -sizes 16 17 -filter shape HNFs.in
```

which would only include HNFs that I have explicitly in the file. The workflow would be:
1. run enumeration as described in #20 to get a list of all HNFs.
2. manually edit that file to have only the ones I want.
3. run enumeration again to create limited `enum.in`.

**Comment by wsmorgan** [comment]
Added in Revision 1.6.0
