### ISSUE TITLE
Structure Range for `makestr.py`

### ISSUE THREAD

**Issue by rosenbrockc** [wsmorgan/phonon-enumeration#28]
It would be helpful to have an option `-all` that makes all the structures in the `enum.out` file. For the range, it would also be good for the `structures` positional argument to take a start/stop range of structure numbers:

``` bash
makestr.py 1 4092
makestr.py all
```

should generate 4092 structure files for the first call and _all_ the structures for the second one.

**Comment by wsmorgan** [comment]
Added in revision 1.5.2.
