### ISSUE TITLE
Enumeration Hangs

### ISSUE THREAD

**Issue by rosenbrockc** [wsmorgan/phonon-enumeration#48]
I am looking for a fixed cell enumeration at 50/50 in a 32 atom cell with fixed shape. I only need two unique configurations. It seems to be taking a really long time to find those two, especially considering that there are some 400,000 unique ones and anything it guesses should be unique. Here are the inputs:

[Archive.zip](https://github.com/wsmorgan/phonon-enumeration/files/664807/Archive.zip)

**Comment by wsmorgan** [comment]
Fixed in Revision 1.8.2.
