### ISSUE TITLE
Python 3 SmithNormalForm error

### ISSUE THREAD

**Issue by jerjorg** [wsmorgan/phonon-enumeration#60]
```
Python 2.7.13
>>> from phenum.grouptheory import SmithNormalForm
>>> H = [[40,0,0],[0,40,0],[0,0,20]]
>>> SmithNormalForm(H)
([[20, 0, 0], [0, 40, 0], [0, 0, 40]], [[1, 0, 1], [0, 1, 0], [-1, 0, 0]], [[0, 0, -1], [0, 1, 0], [1, 0, 2]])
```
```
Python 3.6.1
>>> from phenum.grouptheory import SmithNormalForm
>>> H = [[40,0,0],[0,40,0],[0,0,20]]
>>> SmithNormalForm(H)
SNF conditions not met
```

**Comment by wsmorgan** [comment]
I've tried to reproduce this now in python 3.6.2, 3.5.1, and 3.4.4 with no success. Since python 3.6.2 works but your python 3.6.1 doesn't I believe the issue is actually with python and that you should update your python installation to 3.6.2 and see if the problem persists.

**Comment by wsmorgan** [comment]
The error was due to an out of date version of phenum.
